import gradio as gr
import pandas as pd
import numpy as np
import joblib
import os
import matplotlib.pyplot as plt

# Load your trained model
model = joblib.load("model.joblib")

def predict_churn(frequency, monetary, total_items, avg_basket_size, n_unique_products, country, tenure_days, avg_days_between_purchases):
    # 1. Make the prediction
    df = pd.DataFrame([{
        "frequency": frequency, "monetary": monetary, "total_items": total_items,
        "avg_basket_size": avg_basket_size, "n_unique_products": n_unique_products,
        "country": country, "tenure_days": tenure_days,
        "avg_days_between_purchases": avg_days_between_purchases
    }])
    
    proba = model.predict_proba(df)[0][1]
    
    # 2. Format the main output headline
    if proba >= 0.5:
        risk_status = f"## ⚠️ HIGH RISK: {proba:.2%} chance of churning."
    else:
        risk_status = f"## ✅ SAFE: {proba:.2%} chance of churning."
        
    # 3. Generate the detailed explanation
    explanation_parts = []
    explanation_parts.append("### 🔍 Detailed Explanation & Factors")
    explanation_parts.append("The model made this prediction based on the following customer behaviors:\n")
    
    if frequency < 10:
        explanation_parts.append(f"- **Low Frequency:** This customer only made {frequency} purchases. Low engagement is a strong early warning sign for churn.")
    else:
        explanation_parts.append(f"- **Good Frequency:** This customer has made {frequency} purchases, showing consistent engagement.")
        
    if monetary < 1000:
        explanation_parts.append(f"- **Low Spend:** Total spend is ${monetary:.2f}. Customers who spend less are less invested in the brand.")
    else:
        explanation_parts.append(f"- **High Value:** Total spend is ${monetary:.2f}. High spenders are usually more loyal.")
        
    if avg_days_between_purchases > 90:
        explanation_parts.append(f"- **Infrequent Buyer:** Waits an average of {avg_days_between_purchases} days between purchases. Long gaps often indicate a customer is drifting away.")
    else:
        explanation_parts.append(f"- **Regular Buyer:** Purchases every {avg_days_between_purchases} days on average, indicating a habitual shopper.")
        
    if tenure_days < 180:
        explanation_parts.append(f"- **New Customer:** They have only been a customer for {tenure_days} days. New customers statistically have a higher churn risk.")
    else:
        explanation_parts.append(f"- **Established Customer:** They have been with us for {tenure_days} days. Long-term customers are generally more stable.")
        
    if n_unique_products < 15:
        explanation_parts.append(f"- **Narrow Interest:** Only bought {n_unique_products} unique products. Exploring fewer categories can limit their attachment to the store.")
    else:
        explanation_parts.append(f"- **Diverse Interest:** Bought {n_unique_products} unique products, showing they find multiple items they like.")
        
    explanation_parts.append(f"\n*Note: This prediction was generated by an XGBoost Classifier analyzing historical RFM data.*")

    # Combine text output
    full_text_output = risk_status + "\n\n" + "\n".join(explanation_parts)
    
    # 4. Create the Excel File
    report_data = {
        "Metric": ["Frequency (Orders)", "Monetary (Total $)", "Total Items", "Avg Basket Size ($)", 
                   "Unique Products", "Country", "Tenure (Days)", "Avg Days Between Purchases", 
                   "Churn Probability", "Risk Status"],
        "Value": [frequency, monetary, total_items, avg_basket_size, n_unique_products, 
                  country, tenure_days, avg_days_between_purchases, 
                  f"{proba:.2%}", "HIGH RISK" if proba >= 0.5 else "SAFE"]
    }
    report_df = pd.DataFrame(report_data)
    excel_path = "customer_churn_report.xlsx"
    report_df.to_excel(excel_path, index=False)
    
    # 5. Create the Graph (Pie Chart)
    fig, ax = plt.subplots(figsize=(4, 4))
    labels = ['Churn Risk', 'Safe (Will Stay)']
    sizes = [proba, 1 - proba]
    colors = ['#ff9999', '#66b3ff']
    
    # Only draw the pieces if they are bigger than 0
    valid_labels = [l for l, s in zip(labels, sizes) if s > 0]
    valid_sizes = [s for s in sizes if s > 0]
    valid_colors = [c for c, s in zip(colors, sizes) if s > 0]
    
    ax.pie(valid_sizes, labels=valid_labels, colors=valid_colors, autopct='%1.1f%%', startangle=140, textprops={'fontsize': 12})
    ax.axis('equal')  # Equal aspect ratio ensures that pie is drawn as a circle.
    plt.title("Customer Churn Probability", fontsize=14)
    
    # 6. Extract Feature Importances to explain "how" it was calculated
    rf_model = model.named_steps['clf']
    
    feature_names = ["Frequency", "Monetary", "Total Items", "Avg Basket Size", 
                     "Unique Products", "Country", "Tenure", "Avg Days Between"]
    importances = rf_model.feature_importances_
    
    # SAFETY CHECK: Ensure importances matches the number of feature names
    if len(importances) > len(feature_names):
        # If XGBoost expanded features, just take the top 8
        importances = importances[:len(feature_names)]
    elif len(importances) < len(feature_names):
        # If there are fewer, pad with zeros
        importances = np.pad(importances, (0, len(feature_names) - len(importances)), 'constant')
    
    # Create a DataFrame for the graph
    feat_df = pd.DataFrame({"Feature": feature_names, "Impact": importances})
    feat_df = feat_df.sort_values(by="Impact", ascending=True)
    
    # Plot the Feature Importance Graph
    fig2, ax2 = plt.subplots(figsize=(5, 4))
    ax2.barh(feat_df["Feature"], feat_df["Impact"], color='#2ca02c')
    ax2.set_xlabel("Mathematical Impact on Prediction")
    ax2.set_title("How the Model Calculated This Prediction")
    plt.tight_layout()
    
    # Return the new graph as well!
    return full_text_output, excel_path, fig, fig2

# Build the Web UI with increased limits
inputs = [
    gr.Slider(1, 1000, value=50, label="Frequency (Total Orders)"),
    gr.Slider(1, 200000, value=5000, label="Monetary (Total Spent $)"),
    gr.Slider(1, 50000, value=500, label="Total Items Bought"),
    gr.Slider(1, 20000, value=100, label="Avg Basket Size ($)"),
    gr.Slider(1, 5000, value=50, label="Unique Products Bought"),
    gr.Textbox(value="United Kingdom", label="Country"),
    gr.Slider(1, 3650, value=365, label="Tenure (Days as Customer)"),
    gr.Slider(1, 1000, value=30, label="Avg Days Between Purchases")
]

# Define Multiple Outputs: MUST HAVE 4 ITEMS BECAUSE THE RETURN STATEMENT HAS 4 ITEMS!
outputs = [
    gr.Markdown(label="Prediction & Explanation"),
    gr.File(label="Download Excel Report"),
    gr.Plot(label="Churn Probability Graph"),
    gr.Plot(label="Feature Impact Breakdown")
]

demo = gr.Interface(
    fn=predict_churn, 
    inputs=inputs, 
    outputs=outputs,
    title="🛒 Online Retail Customer Churn Predictor",
    description="Enter customer transaction details to predict churn risk, view explanation, and download report."
)

# Launch
demo.launch(share=True)